# Exported from Render on 2026-08-29T20:49:58Z
version: "1"
services:
- type: web
  name: bot-telegram-moodle
  runtime: python
  repo: https://github.com/pedro1287/botuwu
  plan: free
  envVars:
  - key: BOT_TOKEN
    sync: false
  - key: PYTHON_VERSION
    sync: false
  region: oregon
  buildCommand: pip install --upgrade pip && pip install -r requirements.txt
  startCommand: python main.py
  autoDeployTrigger: commit

